version: '2'
services:
    smartpass-app:
        image: smartpass
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://smartpass-mariadb:3306/smartpass
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    smartpass-mariadb:
        extends:
            file: mariadb.yml
            service: smartpass-mariadb
